require("lazy").setup({
  require("lazy.config.plenary"),
  require("lazy.config.popup"),
  require("lazy.config.fugitive"),
  require("lazy.config.cursorline"),
  require("lazy.config.bracey"),
  require("lazy.config.markdown"),
  require("lazy.config.renamer"),
  require("lazy.config.autotag"),
  require("lazy.config.spectre"),
  { "tpope/vim-surround" },
  require("lazy.config.regexplainer"),
  require("lazy.config.hop"),
  require("lazy.config.rainbow"),
  require("lazy.config.alpha"),
  require("lazy.config.blankline"),
  require("lazy.config.winshift"),
  require("lazy.config.telescope"),
  { "folke/tokyonight.nvim" },
  require("lazy.config.windline"),
  require("lazy.config.gitsigns"),
  require("lazy.config.treesitter"),
  "nvim-treesitter/nvim-treesitter-textobjects",
  "romgrk/nvim-treesitter-context",
  require("lazy.config.lspsaga"),
  require("lazy.config.trouble"),
  "neovim/nvim-lspconfig",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-cmdline",
  require("lazy.config.snippy"),
  require("lazy.config.cmp"),
  "dcampos/cmp-snippy",
  "tversteeg/registers.nvim",
  -- require("lazy.config.autopairs"),
  require("lazy.config.insx"),
  { "weilbith/nvim-code-action-menu", cmd = "CodeActionMenu" },
  require("lazy.config.bufferline"),
  require("lazy.config.tree"),
  require("lazy.config.project"),
  "nathom/filetype.nvim",
  require("lazy.config.twilight"),
  require("lazy.config.formatter"),
  require("lazy.config.which-key"),
  "JoosepAlviste/nvim-ts-context-commentstring",
  require("lazy.config.comment"),
  require("lazy.config.stablize"),
  { "ellisonleao/glow.nvim" },
  require("lazy.config.rest"),
  require("lazy.config.hlslens"),
  require("lazy.config.rust"),
  require("lazy.config.crates"),
  { "mfussenegger/nvim-dap" },
  require("lazy.config.colorizer"),
  { "haringsrob/nvim_context_vt" },
  { "pgdouyon/vim-yin-yang" },
  require("lazy.config.escap"),
  require("lazy.config.numb"),
  { "github/copilot.vim" },
  require("lazy.config.bisquits"),
  -- require("lazy.config.neoscroll"))
  require("lazy.config.noice"),
  require("lazy.config.portal"),
})
