-- require('wlsample.airline')
require('wlsample.airline_anim')
-- require('wlsample.bubble')
-- require('wlsample.bubble2')
-- require('wlsample.evil_line')
-- require('wlsample.vscode')
-- require('wlsample.basic')
-- require('wlsample.wind')
-- require('wlsample.airline_luffy')
